// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	global "example/be/service/api/internal/handler/global"
	"example/be/service/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取系统时间
				Method:  http.MethodGet,
				Path:    "/api/global/datetime",
				Handler: global.GetTimeHandler(serverCtx),
			},
		},
	)
}
